import { Lead, Cadence, CadenceStep } from './types';

// Mock leads data
export const mockLeads: Lead[] = [
  {
    id: 'lead-1',
    companyname: 'Acme Corporation',
    contactName: 'John Smith',
    email: 'john@acme.com',
    phone: '(555) 123-4567',
    status: 'prospected',
    priority: 'high',
    value: 25000,
    createdDate: Date.now() - 5 * 24 * 60 * 60 * 1000,
    nextActivity: 'Follow-up call',
  },
  {
    id: 'lead-2',
    companyname: 'Globex Inc',
    contactName: 'Jane Doe',
    email: 'jane@globex.com',
    phone: '(555) 987-6543',
    status: 'contacted',
    priority: 'medium',
    value: 15000,
    createdDate: Date.now() - 10 * 24 * 60 * 60 * 1000,
    nextActivity: 'Product demo',
  },
  {
    id: 'lead-3',
    companyname: 'Initech',
    contactName: 'Michael Johnson',
    email: 'michael@initech.com',
    phone: '(555) 456-7890',
    status: 'proposal',
    priority: 'high',
    value: 45000,
    createdDate: Date.now() - 15 * 24 * 60 * 60 * 1000,
    nextActivity: 'Proposal review',
  },
  {
    id: 'lead-4',
    companyname: 'Wayne Enterprises',
    contactName: 'Bruce Wayne',
    email: 'bruce@wayne.com',
    phone: '(555) 321-7654',
    status: 'closed',
    priority: 'high',
    value: 100000,
    createdDate: Date.now() - 20 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'lead-5',
    companyname: 'Stark Industries',
    contactName: 'Tony Stark',
    email: 'tony@stark.com',
    phone: '(555) 789-0123',
    status: 'prospected',
    priority: 'medium',
    value: 35000,
    createdDate: Date.now() - 3 * 24 * 60 * 60 * 1000,
    nextActivity: 'Initial outreach',
  },
  {
    id: 'lead-6',
    companyname: 'Daily Planet',
    contactName: 'Clark Kent',
    email: 'clark@dailyplanet.com',
    phone: '(555) 234-5678',
    status: 'contacted',
    priority: 'low',
    value: 8000,
    createdDate: Date.now() - 7 * 24 * 60 * 60 * 1000,
    nextActivity: 'Follow-up email',
  },
  {
    id: 'lead-7',
    companyname: 'Cyberdyne Systems',
    contactName: 'Miles Dyson',
    email: 'miles@cyberdyne.com',
    phone: '(555) 876-5432',
    status: 'proposal',
    priority: 'high',
    value: 75000,
    createdDate: Date.now() - 12 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'lead-8',
    companyname: 'Umbrella Corporation',
    contactName: 'Albert Wesker',
    email: 'wesker@umbrella.com',
    phone: '(555) 345-6789',
    status: 'closed',
    priority: 'medium',
    value: 50000,
    createdDate: Date.now() - 25 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'lead-9',
    companyname: 'Dunder Mifflin',
    contactName: 'Michael Scott',
    email: 'michael@dundermifflin.com',
    phone: '(555) 567-8901',
    status: 'prospected',
    priority: 'low',
    value: 5000,
    createdDate: Date.now() - 2 * 24 * 60 * 60 * 1000,
    nextActivity: 'Intro call',
  },
  {
    id: 'lead-10',
    companyname: 'Pied Piper',
    contactName: 'Richard Hendricks',
    email: 'richard@piedpiper.com',
    phone: '(555) 678-9012',
    status: 'contacted',
    priority: 'high',
    value: 20000,
    createdDate: Date.now() - 8 * 24 * 60 * 60 * 1000,
    nextActivity: 'Technical discussion',
  }
];

// Mock cadences data
export const mockCadences: Cadence[] = [
  {
    id: 'cadence-1',
    name: 'Cold Outreach Sequence',
    status: 'active',
    duration: 14,
    steps: [
      {
        day: 1,
        type: 'Email',
        subject: 'Introduction and value proposition',
        completed: true,
        sentCount: 85,
        responseCount: 12,
      },
      {
        day: 3,
        type: 'Email',
        subject: 'Case study - success story',
        completed: true,
        sentCount: 73,
        responseCount: 8,
      },
      {
        day: 5,
        type: 'Call',
        subject: 'Follow-up call',
        completed: true,
        sentCount: 65,
        responseCount: 15,
      },
      {
        day: 8,
        type: 'Email',
        subject: 'Additional resources',
        completed: false,
        sentCount: 0,
        responseCount: 0,
      },
      {
        day: 14,
        type: 'Email',
        subject: 'Final check-in',
        completed: false,
        sentCount: 0,
        responseCount: 0,
      }
    ]
  },
  {
    id: 'cadence-2',
    name: 'Product Demo Follow-up',
    status: 'active',
    duration: 10,
    steps: [
      {
        day: 1,
        type: 'Email',
        subject: 'Thank you for your time',
        completed: true,
        sentCount: 42,
        responseCount: 18,
      },
      {
        day: 3,
        type: 'Email',
        subject: 'Additional features you might like',
        completed: true,
        sentCount: 24,
        responseCount: 6,
      },
      {
        day: 7,
        type: 'Call',
        subject: 'Check-in call',
        completed: false,
        sentCount: 0,
        responseCount: 0,
      },
      {
        day: 10,
        type: 'Email',
        subject: 'Special offer',
        completed: false,
        sentCount: 0,
        responseCount: 0,
      }
    ]
  },
  {
    id: 'cadence-3',
    name: 'Event Invitation Sequence',
    status: 'draft',
    duration: 7,
    steps: [
      {
        day: 1,
        type: 'Email',
        subject: 'Exclusive webinar invitation',
        completed: false,
        sentCount: 0,
        responseCount: 0,
      },
      {
        day: 3,
        type: 'Email',
        subject: 'Reminder: Upcoming webinar',
        completed: false,
        sentCount: 0,
        responseCount: 0,
      },
      {
        day: 5,
        type: 'Email',
        subject: 'Last chance to register',
        completed: false,
        sentCount: 0,
        responseCount: 0,
      },
      {
        day: 7,
        type: 'Email',
        subject: 'Webinar materials',
        completed: false,
        sentCount: 0,
        responseCount: 0,
      }
    ]
  },
  {
    id: 'cadence-4',
    name: 'Customer Onboarding',
    status: 'paused',
    duration: 21,
    steps: [
      {
        day: 1,
        type: 'Email',
        subject: 'Welcome to our platform',
        completed: true,
        sentCount: 120,
        responseCount: 78,
      },
      {
        day: 3,
        type: 'Email',
        subject: 'Getting started guide',
        completed: true,
        sentCount: 120,
        responseCount: 65,
      },
      {
        day: 7,
        type: 'Call',
        subject: 'Onboarding check-in',
        completed: true,
        sentCount: 75,
        responseCount: 40,
      },
      {
        day: 14,
        type: 'Email',
        subject: 'Advanced features',
        completed: false,
        sentCount: 0,
        responseCount: 0,
      },
      {
        day: 21,
        type: 'Email',
        subject: 'Success check-in',
        completed: false,
        sentCount: 0,
        responseCount: 0,
      }
    ]
  },
  {
    id: 'cadence-5',
    name: 'Re-engagement Campaign',
    status: 'active',
    duration: 14,
    steps: [
      {
        day: 1,
        type: 'Email',
        subject: 'We miss you - special offer',
        completed: true,
        sentCount: 200,
        responseCount: 15,
      },
      {
        day: 5,
        type: 'Email',
        subject: 'New features you might have missed',
        completed: true,
        sentCount: 185,
        responseCount: 12,
      },
      {
        day: 9,
        type: 'Email',
        subject: 'Last chance offer',
        completed: false,
        sentCount: 0,
        responseCount: 0,
      },
      {
        day: 14,
        type: 'Email',
        subject: 'Final outreach',
        completed: false,
        sentCount: 0,
        responseCount: 0,
      }
    ]
  }
];